version: '3.8'
services:
  realtor-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: realtor
    networks:
      - ebweb
networks:
  ebweb:
